# Yarn 配置文件
# 優化 Cloudflare Pages 建置

# 啟用 PnP (Plug'n'Play) 模式
nodeLinker: pnp

# 設置 npm 註冊表
npmRegistryServer: "https://registry.npmjs.org"

# 啟用零安裝模式
enableGlobalCache: true

# 設置依賴檢查模式
enableStrictSsl: true

# 優化依賴解析
enableScripts: true

# 設置平台和架構
supportedArchitectures:
  os: [linux, darwin, win32]
  cpu: [x64, arm64]
